export const CITY_LIST_REQUEST="CITY_LIST_REQUEST";
export const CITY_LIST_SUCCESS="CITY_LIST_SUCCESS";
export const CITY_LIST_FAIL="CITY_LIST_FAIL";

export const DISTRICT_LIST_REQUEST="DISTRICT_LIST_REQUEST";
export const DISTRICT_LIST_SUCCESS="DISTRICT_LIST_SUCCESS";
export const DISTRICT_LIST_FAIL="DISTRICT_LIST_FAIL";

export const SQUARE_LIST_REQUEST="SQUARE_LIST_REQUEST";
export const SQUARE_LIST_SUCCESS="SQUARE_LIST_SUCCESS";
export const SQUARE_LIST_FAIL="SQUARE_LIST_FAIL";


